server:
  port: 9012

spring:
  redis:
    host: 43.138.127.205
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    redisson:
#      file: classpath:redisson.yaml
      config: |
        singleServerConfig:
          password: 123456
          address: "redis://43.138.127.205:6379"
          database: 0
          threads: 0
          nettyThreads: 0
          codec: !<org.redisson.codec.FstCodec> {}
          transportMode: "NIO"