spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          password: 123456
          address: "redis://43.138.127.205:6379"
          database: 0
          threads: 0
          nettyThreads: 0
          codec: !<org.redisson.codec.FstCodec> {}
          transportMode: "NIO"