server:
  port: 8030
spring:
  application:
    name: alibaba-sentinel
  cloud:
    sentinel:
      datasource:
        flow :  # flow 是数据源名,可随意配置
          file:
            file: classpath:sentinel/FlowRule.json
            data-type: json
            rule-type: flow
        degrade:  # degrade 是数据源名,可随意配置
          file:
            file:  classpath:sentinel/DegradeRule.json
            data-type: json
            rule-type: degrade
