server:
  port: 8100
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-provider
          uri: http://localhost:8765
          predicates:
            - Path=/provider/**
