server:
  port: 8100
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.127.205:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-provider
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
