server:
  port: 8050

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.yang.entity

spring:
  datasource:
    url: jdbc:mysql://43.138.127.205:3306/mysqlTest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.yang.dao: debug
