server:
  port: 8050

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://43.138.127.205:3306/mysqlTest
    username: root
    password: root

logging:
  level:
    com.yang.dao: debug