server:
  port: 8060

spring:
  redis:
    host: 43.138.127.205
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0