server:
  port: 8060

spring:
  redis:
    host: 117.72.17.173
    port: 6379
    database: 0
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: -1
#        min-idle: 2
    password: jichi1234