server:
  port: 8801
spring:
  cloud:
    nacos:
      config:
        server-addr: 43.138.127.205:8848
        name: nacos-config.yaml
        group: DEVELOP_GROUP
        file-extension: yaml
        refresh-enabled: true
  application:
    name: nacos-config


